### ISSUE TITLE
GPT not accessing website

### ISSUE THREAD

**Issue by MahVRO** [darknight1050/CrashReporter#1]
Hi i tried to create a ChatGPT that retrieve the last 5 lines under `backtrace`, but it seems like its not working at all because he cannot access this website (it's still loading).
So i wanted to know if its GPT's browing tool fault or the website is just not made for it.
Thanks!

**Comment by darknight1050** [comment]
What URL exactly do you give GPT? Do you use the API routes? The frontend makes a request to the API aswell and maybe that's not compatible for GPT? (because it won't execute the javascript that does the request)

**Comment by MahVRO** [comment]
Since im not a professional in coding or programming, I simply gave him the basic url "analyzer.questmodding.com/crashes/", told him to click on the latest four-digits code at the top of the page but apparently any of the pages wont load for him (ChatGPT).
I don't even know how APIs really works but i've heard that these are for automations and things.

**Comment by MahVRO** [comment]
Sorry closed it cause now i know how to use it
